name: supabase_easy
description: "Easy-to-use Supabase helpers for Flutter"
version: 0.0.1
homepage: https://github.com/yashprajapati/supabase_easy
repository: https://github.com/yourname/supabase_easy

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  json_annotation: ^4.10.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.12.0

flutter:
  
  plugin:
    platforms:
      android:
        package: com.example.supabase_easy
        pluginClass: SupabaseEasyPlugin
      ios:
        pluginClass: SupabaseEasyPlugin

