name: supabase_easy
description: "A powerful and lightweight Supabase wrapper for Flutter that reduces boilerplate for Auth, Database CRUD, and Real-time listeners by 60-70%."
version: 0.0.4
homepage: https://github.com/yashprajapati/supabase_easy
repository: https://github.com/yashprajapati/supabase_easy

environment:
  sdk: ^3.10.7
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  
  plugin:
    platforms:
      android:
        package: com.example.supabase_easy
        pluginClass: SupabaseEasyPlugin
      ios:
        pluginClass: SupabaseEasyPlugin

